# <color:#ab1c15> ToiletMC>> 
max_mspt: 185
message:
  lag_broadcast: |-
    <color:#ab1c15><hover:show_text:'这是实时消息，我们有一个性能监测程序。当服务器运行缓慢时，它会自动发出警告！'><b>[WARNING]服务器当前已过载！此刻MSPT：%mspt%</b></color>
    <b>请即刻离开大型刷怪塔、粘液基地、村民交易所等卡服地点，谢谢合作！</b>